### ISSUE TITLE
Preventing the game from reloading

### ISSUE THREAD

**Issue by RaR1991** [Helco/ZZSpeeds#4]
is it possible please  to stop the game from reloading when I switch to another window such as CE

**Comment by Helco** [comment]
It certainly is: [here you go](https://github.com/Helco/ZZSpeeds/releases/tag/1.5)

Keep in mind that this currently only works in __windowed mode__. Also the game is not paused, you have to pause yourself (by pressing escape in the overworld or F1 in fights)  if necessary.

**Comment by RaR1991** [comment]
oh great!! thank you
