### ISSUE TITLE
Running zanzarah via WindowedZanzarah.exe makes the game playing at ~111fps

### ISSUE THREAD

**Issue by ArenaMMORPG** [Helco/ZZSpeeds#8]
Is there any possible solutions to 'unlock' fps, as it seems to be with dgVoodoo?
So it's like running original zanzarah.exe with dgVoodoo makes fps to be unlocked, but with windowedzanzarah.exe approximately ~110-115fps

**Comment by Helco** [comment]
yes there is, you can pass an additional parameter to WindowedZanzarah.exe `-fps(10000)` which effectively disables the frame limiter - by default it is set to 120.
The easiest way for this is to use a shortcut ([this site explains it well](https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/)).

This limiter was added deliberately as some of the game logic unfortunately breaks down at higher framerates (say 500+). The most clear symptom I have seen is going into a fairy fight, fly around a bit to drain the stamina and then try to land for replenishing the stamina. If the framerate is too high the stamina will come back only very slowly if at all and the fairy will bounce a bit as if it never quite reaches the floor.

**Comment by ArenaMMORPG** [comment]
Thanks a lot man! It's finally done, windowed + i can alt tab + fps with any hz monitor, its so cool :)

**Comment by ArenaMMORPG** [comment]
also, a very little 'problem' is that it seems for me, that with windowed zanzarah

**Comment by ArenaMMORPG** [comment]
also, there is a very little 'problem' is that it seems for me, that with windowed zanzarah game's window is a little bit 'upper' with borderless gaming, than my monitor shows, in the screen riva tuner's monitoring is a little bit upper, than the top of the monitor, i actually don't know how to describe it professionally :D 

https://imgur.com/a/HvsFANM

**Comment by Helco** [comment]
I am afraid for this I do not have a good answer, with Zanzarah + dgVoodoo + WindowedZanzarah + the widescreen patch + Borderless Gaming the precarious stack of window controlling applications is at a point where I cannot predict what is going on.

I guess what I would do is to check whether only riva tuner is showing incorrectly or the game actually being cropped. Off the top of my head I only recall during fights where UI is fixed at the top of the screen (the list of enemy icons).

**Comment by ArenaMMORPG** [comment]
Okay, thanks again for professional clarification, good luck!
